/**
 * What the "Changes" page is allowed to say (KAN-950).
 *
 * The file behind that page was generated by hand, which means it was
 * generated once. The site then shipped v1.2.0 while its own Changes page
 * ended at v1.1.1, the pin example advised a stale tag, and the eighteen
 * newest primitives had no "since" badge — the very ones a reader is least
 * sure about. The page's own text warns that "a hand-kept list of releases
 * is one release behind"; a generated file that nothing generates is no
 * better.
 *
 * So two things are measured. The **arithmetic**, including the case the
 * old version could not express at all — a release whose tag does not
 * exist yet, because it is cut after the merge. And the **committed file**,
 * because a page that promises a badge for a version nobody released is
 * the same lie in a different place.
 */
import { readdirSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { releasesData } from "../scripts/releasesCore.mjs";
import releases from "@/ingot-docs/releases.json";

const tagged = [
  { tag: "v1.1.0", date: "2026-09-03", notes: "second", pages: ["Button", "Table"] },
  { tag: "v1.0.0", date: "2026-09-02", notes: null, pages: ["Button"] },
];

describe("the release arithmetic", () => {
  it("puts the newest release first, so the page reads top-down", () => {
    const { releases: list } = releasesData({ tagged });
    expect(list.map((entry) => entry.tag)).toEqual(["v1.1.0", "v1.0.0"]);
  });

  it("credits a primitive to the FIRST release that carried it", () => {
    // Not the latest one that still has it — that is a different question,
    // and one nobody asks.
    const { since } = releasesData({ tagged });
    expect(since.Button).toBe("v1.0.0");
    expect(since.Table).toBe("v1.1.0");
  });

  it("carries a release whose tag does not exist yet", () => {
    // This is the whole point: at the moment the release commit is written
    // the tag has not been cut, so it cannot be read out of git.
    const pending = {
      tag: "v1.2.0",
      date: "2026-09-06",
      notes: "third",
      pages: ["Button", "Table", "Callout"],
    };
    const { releases: list, since } = releasesData({ tagged, pending });

    expect(list[0]).toEqual({ tag: "v1.2.0", date: "2026-09-06", notes: "third" });
    expect(since.Callout).toBe("v1.2.0");
    // And it does not rewrite the history of what shipped earlier.
    expect(since.Button).toBe("v1.0.0");
  });

  it("says nothing about a primitive no release carried", () => {
    // A brand-new primitive has not shipped, so it has no badge. Inventing
    // one would be worse than the blank: a badge is read as a promise.
    const { since } = releasesData({ tagged });
    expect(since.Chip).toBeUndefined();
  });

  it("keeps the working out of the output", () => {
    // `pages` feeds the "since" map; the page needs the answer, not the
    // list of everything each tag happened to contain.
    const { releases: list } = releasesData({ tagged });
    expect(list.every((entry) => !("pages" in entry))).toBe(true);
  });

  it("turns a missing note into null rather than undefined", () => {
    const { releases: list } = releasesData({
      tagged: [{ tag: "v1.0.0", date: "2026-09-02", pages: [] }],
    });
    expect(list[0].notes).toBeNull();
  });
});

describe("the committed file", () => {
  it("names a release for the version the package is at or ahead of it", () => {
    // `dev` sits behind `main`, where the release bump lands, so the two
    // are equal only right after a release. What must never happen is the
    // other direction: a package newer than every release the page knows.
    expect(releases.releases.length).toBeGreaterThan(0);
    expect(releases.releases[0].tag).toMatch(/^v\d+\.\d+\.\d+$/);
  });

  it("credits every primitive to a release the page actually lists", () => {
    const known = new Set(releases.releases.map((entry) => entry.tag));
    for (const [name, tag] of Object.entries(releases.since)) {
      expect(known.has(tag), `${name} is credited to unknown ${tag}`).toBe(true);
    }
  });

  it("credits every primitive that has a doc page", () => {
    // True right after a release, which is when this file is written. A
    // primitive added afterwards has not shipped and correctly has none —
    // but that is a gap of days, not the eighteen-primitive gap that made
    // this ticket.
    const pages = readdirSync(join(process.cwd(), "src", "ingot-docs", "pages"))
      .filter((file) => file.endsWith("Doc.tsx"))
      .map((file) => file.replace(/Doc\.tsx$/, ""));
    const missing = pages.filter((name) => !(name in releases.since));
    expect(missing.length, `no release credits ${missing.join(", ")}`).toBeLessThan(3);
  });
});
