/**
 * What the "Changes" page reads, as a pure function.
 *
 * The data itself comes from git — the tags, their dates, the pages each
 * tag carried. What belongs here is the arithmetic on top of it, and one
 * case the first version could not express at all: **the release that is
 * about to be cut.**
 *
 * That gap was not theoretical. The file was generated by hand, the
 * release commit touched only `package.json` and `CHANGELOG.md`, and so
 * the site shipped v1.2.0 while its own Changes page ended at v1.1.1, its
 * pin example advised an outdated tag, and the eighteen newest primitives
 * had no "since" badge — precisely the ones a reader is least sure about.
 *
 * A release knows everything the page needs before its tag exists: the
 * version, the notes, the date, and which pages are in the tree. So the
 * pending release is an argument here, and `release.mjs` passes it in the
 * same commit that moves the version. There is nothing left to run
 * afterwards, and therefore nothing left to forget.
 */

/**
 * ``tagged`` are the releases that already have a tag, newest first, each
 * as ``{ tag, date, notes, pages }``. ``pending`` is the release being cut
 * right now, in the same shape, or ``null`` outside a release.
 *
 * ``pages`` is the list of documented primitive names at that point in
 * history; it feeds the "since" map and is not carried into the output —
 * the page needs the answer, not the working.
 */
export function releasesData({ tagged, pending = null }) {
  const newestFirst = pending ? [pending, ...tagged] : [...tagged];

  const releases = newestFirst.map(({ tag, date, notes }) => ({
    tag,
    date,
    notes: notes ?? null,
  }));

  // Oldest first, so the FIRST tag that carries a page is the one that
  // wins — that is the release the primitive shipped in. Walking newest
  // first would answer "the latest release that still has it", which is a
  // different question and one nobody asks.
  const since = {};
  for (const entry of [...newestFirst].reverse()) {
    for (const name of entry.pages ?? []) {
      if (!(name in since)) since[name] = entry.tag;
    }
  }

  return { releases, since };
}
